FROM node:20.5.1-bookworm-slim

WORKDIR /usr/src/app

COPY . .

RUN yarn cache clean --force

RUN yarn config delete proxy

RUN npm config rm proxy

RUN npm config rm https-proxy

RUN yarn --network-timeout 100000

RUN yarn build:development

CMD [ "yarn", "start:development" ]

