version: "3"
name: marketplace
services:
  frontend:
    stdin_open: true
    tty: true
    build: 
      context: ../../
      dockerfile: ./.docker/frontend/Dockerfile.stag
    image: careplace/marketplace-frontend-stag:latest
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    