export const DISTRICTS = [
  { text: 'Aveiro', value: 'Aveiro' },
  { text: 'Beja', value: 'Beja' },
  { text: 'Braga', value: 'Braga' },
  { text: 'Bragança', value: 'Bragança' },
  { text: 'Castelo Branco', value: 'Castelo Branco' },
  { text: 'Coimbra', value: 'Coimbra' },
  { text: 'Évora', value: 'Évora' },
  { text: 'Faro', value: 'Faro' },
  { text: 'Guarda', value: 'Guarda' },
  { text: 'Leiria', value: 'Leiria' },
  { text: 'Lisboa', value: 'Lisboa' },
  { text: 'Portalegre', value: 'Portalegre' },
  { text: 'Porto', value: 'Porto' },
  { text: 'Santarém', value: 'Santarém' },
  { text: 'Setúbal', value: 'Setúbal' },
  { text: 'Viana do Castelo', value: 'Viana do Castelo' },
  { text: 'Vila Real', value: 'Vila Real' },
  { text: 'Viseu', value: 'Viseu' },
];
