name: '[STAGING] Continuous Integration (CI)'

on:
  push:
    branches: ['staging']
  pull_request:
    branches: ['staging']

jobs:
  dependencies:
    name: Dependency Management
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Branch name
        run: echo running on branch '${GITHUB_REF##*/}'
      - name: Install dependencies
        run: yarn install
      - name: Dependency Management
        run: yarn depcheck

  lint:
    name: Lint
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Branch name
        run: echo running on branch '${GITHUB_REF##*/}'
      - name: Install dependencies
        run: yarn install
      - name: Format
        run: yarn prettier-check
      - name: Lint
        run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Branch name
        run: echo running on branch '${GITHUB_REF##*/}'
      - name: Build the Docker image
        run: docker build . --file .docker/frontend/Dockerfile.stag --tag careplace-marketplace-build-staging:$(date +%s)

  test:
    name: Test
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

  security:
    name: Security
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Branch name
        run: echo running on branch '${GITHUB_REF##*/}'
      - name: Install dependencies
        run: yarn install
      - name: Snyk Auth
        run: npx snyk auth ${{ secrets.SNYK_API_TOKEN }}
      - name: Snyk Policy
        run: npx snyk policy
      - name: Snyk Test Code
        run: npx snyk test --severity-threshold=high
      - name: Build the Docker image
        run: docker build . --file .docker/frontend/Dockerfile.stag --tag careplace/marketplace-web:stag
      - name: Snyk Test Docker Image
        run: npx snyk container test careplace/marketplace-web:stag --file=.docker/frontend/Dockerfile.stag --severity-threshold=high
