name: Docker Image CI

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Branch name
        run: echo running on branch '${GITHUB_REF##*/}'
      - name: Build the Docker image
        # We use the Staging Dockerfile to test the react build
        # Staging Dockerfile: npm run build -> npm start
        # Dev Dockerfile: npm dev
        run: docker build . --file .docker/frontend/Dockerfile.stag --tag careplace-marketplace-frontend-build-dev-${GITHUB_REF##*/}:$(date +%s)
